name: Run Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Bruno
      run: npm install -g brunocli

    - name: Run Bruno Tests
      run: bruno run <path_to_your_test.yaml>
